org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17.21

# Mod Properties
mod_version=1.1.0
maven_group=dev.fweigel
archives_base_name=sulfurcubesplus

# Dependencies
fabric_version=0.161.0+26.3
